################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ARM_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_max_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_min_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_power_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_power_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_power_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_power_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_power_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_power_q7.c \
../ARM_DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_std_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_std_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_std_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_std_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_std_q31.c \
../ARM_DSP/Source/StatisticsFunctions/arm_var_f16.c \
../ARM_DSP/Source/StatisticsFunctions/arm_var_f32.c \
../ARM_DSP/Source/StatisticsFunctions/arm_var_f64.c \
../ARM_DSP/Source/StatisticsFunctions/arm_var_q15.c \
../ARM_DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./ARM_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_max_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_min_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_power_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_power_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_power_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_power_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_power_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_power_q7.o \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_std_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_std_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_std_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_std_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_std_q31.o \
./ARM_DSP/Source/StatisticsFunctions/arm_var_f16.o \
./ARM_DSP/Source/StatisticsFunctions/arm_var_f32.o \
./ARM_DSP/Source/StatisticsFunctions/arm_var_f64.o \
./ARM_DSP/Source/StatisticsFunctions/arm_var_q15.o \
./ARM_DSP/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./ARM_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_max_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_min_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_power_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_power_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_power_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_power_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_power_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_power_q7.d \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_std_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_std_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_std_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_std_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_std_q31.d \
./ARM_DSP/Source/StatisticsFunctions/arm_var_f16.d \
./ARM_DSP/Source/StatisticsFunctions/arm_var_f32.d \
./ARM_DSP/Source/StatisticsFunctions/arm_var_f64.d \
./ARM_DSP/Source/StatisticsFunctions/arm_var_q15.d \
./ARM_DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
ARM_DSP/Source/StatisticsFunctions/%.o ARM_DSP/Source/StatisticsFunctions/%.su: ../ARM_DSP/Source/StatisticsFunctions/%.c ARM_DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM7 -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H745xx -c -I../Core/Inc -I"C:/Users/khalil/STM32CubeIDE/workspace_1.4.0/Oxy/Test_Oxymetre_3/CM7/ARM_DSP/Include" -I"C:/Users/khalil/STM32CubeIDE/workspace_1.4.0/Oxy/Test_Oxymetre_3/CM7/ARM_DSP/PrivateInclude" -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-ARM_DSP-2f-Source-2f-StatisticsFunctions

clean-ARM_DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./ARM_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./ARM_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./ARM_DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_accumulate_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su
	-$(RM) ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_max_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_max_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_max_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_mean_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_mean_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_min_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_min_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_min_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f64.d
	-$(RM) ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_mse_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_mse_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_power_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_power_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_power_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_power_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_power_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_power_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_power_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_power_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_power_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_power_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_power_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_power_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_power_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_power_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_power_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_power_q7.d ./ARM_DSP/Source/StatisticsFunctions/arm_power_q7.o ./ARM_DSP/Source/StatisticsFunctions/arm_power_q7.su ./ARM_DSP/Source/StatisticsFunctions/arm_rms_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_rms_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_rms_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_rms_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_rms_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_rms_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_rms_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_rms_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_rms_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_rms_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_rms_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_rms_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_std_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_std_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_std_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_std_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_std_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_std_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_std_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_std_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_std_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_std_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_std_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_std_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_std_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_std_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_std_q31.su ./ARM_DSP/Source/StatisticsFunctions/arm_var_f16.d ./ARM_DSP/Source/StatisticsFunctions/arm_var_f16.o ./ARM_DSP/Source/StatisticsFunctions/arm_var_f16.su ./ARM_DSP/Source/StatisticsFunctions/arm_var_f32.d ./ARM_DSP/Source/StatisticsFunctions/arm_var_f32.o ./ARM_DSP/Source/StatisticsFunctions/arm_var_f32.su ./ARM_DSP/Source/StatisticsFunctions/arm_var_f64.d ./ARM_DSP/Source/StatisticsFunctions/arm_var_f64.o ./ARM_DSP/Source/StatisticsFunctions/arm_var_f64.su ./ARM_DSP/Source/StatisticsFunctions/arm_var_q15.d ./ARM_DSP/Source/StatisticsFunctions/arm_var_q15.o ./ARM_DSP/Source/StatisticsFunctions/arm_var_q15.su ./ARM_DSP/Source/StatisticsFunctions/arm_var_q31.d ./ARM_DSP/Source/StatisticsFunctions/arm_var_q31.o ./ARM_DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-ARM_DSP-2f-Source-2f-StatisticsFunctions

