################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ARM_DSP/Source/FilteringFunctions/FilteringFunctionsF16.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_conv_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_f64.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_q15.c \
../ARM_DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./ARM_DSP/Source/FilteringFunctions/FilteringFunctionsF16.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_conv_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_f64.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_q15.o \
./ARM_DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./ARM_DSP/Source/FilteringFunctions/FilteringFunctionsF16.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_conv_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_f64.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_q15.d \
./ARM_DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
ARM_DSP/Source/FilteringFunctions/%.o ARM_DSP/Source/FilteringFunctions/%.su: ../ARM_DSP/Source/FilteringFunctions/%.c ARM_DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM7 -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H745xx -c -I../Core/Inc -I"C:/Users/khalil/STM32CubeIDE/workspace_1.4.0/Oxy/Test_Oxymetre_3/CM7/ARM_DSP/Include" -I"C:/Users/khalil/STM32CubeIDE/workspace_1.4.0/Oxy/Test_Oxymetre_3/CM7/ARM_DSP/PrivateInclude" -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-ARM_DSP-2f-Source-2f-FilteringFunctions

clean-ARM_DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./ARM_DSP/Source/FilteringFunctions/FilteringFunctionsF16.d ./ARM_DSP/Source/FilteringFunctions/FilteringFunctionsF16.o ./ARM_DSP/Source/FilteringFunctions/FilteringFunctionsF16.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_f32.o
	-$(RM) ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_conv_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_conv_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_conv_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f64.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f64.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_f64.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_correlate_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_f64.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_f64.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_f64.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q15.d
	-$(RM) ./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f64.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f64.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_f64.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./ARM_DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su
	-$(RM) ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_q15.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_q15.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_q15.su ./ARM_DSP/Source/FilteringFunctions/arm_lms_q31.d ./ARM_DSP/Source/FilteringFunctions/arm_lms_q31.o ./ARM_DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-ARM_DSP-2f-Source-2f-FilteringFunctions

